<?php

//This file will write a php config file to be included during execution of all timecard file for configuration.

// deny all but system admins
$canEdit = !getDenyEdit( 'system' );
if (!$canEdit) {
	$AppUI->redirect( "m=public&a=access_denied" );
}

$CONFIG_FILE = "./modules/timecard/config.php";

$AppUI->savePlace();

//All config options, their descriptions and their default values are defined here.  
$config_options = array(
	"can_edit_other_worksheets" => array(
		"description" => $AppUI->_('Allow editing of other users time cards.'),
		"value" => 0
	),
	"show_other_worksheets" => array(
		"description" => $AppUI->_('Allow users to see other users timesheets.'),
		"value" => 0
	),
	"allow_reporting" => array(
		"description" => $AppUI->_('Allow users access to the reporting area.'),
		"value" => 0
	),
	"integrate_with_helpdesk" => array(
		"description" => $AppUI->_('Allow integration with HelpDesk module.'),
		"value" => 0
	)
);

//if this is a submitted page, overwrite the config file.
if(dPgetParam( $_POST, "Save", '' )!=''){

	if (is_writable($CONFIG_FILE)) {
		if (!$handle = fopen($CONFIG_FILE, 'w')) {
			$AppUI->setMsg( $CONFIG_FILE." ".$AppUI->_('cannot be opened.'), UI_MSG_ERROR );
			exit;
		}

		if (fwrite($handle, "<?php //Do not edit this file by hand, it will be overwritting by the configuration utility. \n") === FALSE) {
			$AppUI->setMsg( $CONFIG_FILE." ".$AppUI->_('cannot be written to.'), UI_MSG_ERROR );
			exit;
		} else {
			foreach ($config_options as $key=>$value){
				//$TIMECARD_CONFIG['can_edit_other_worksheets'] = 1;
				$val = isset($_POST[$key])?"1":"0";

				fwrite($handle, "\$TIMECARD_CONFIG['".$key."'] = ".$val.";\n");
			}

			fwrite($handle, "?> \n");
			$AppUI->setMsg( $CONFIG_FILE." ".$AppUI->_('has been successfully updated.'), UI_MSG_OK );
			fclose($handle);
		}
	} else {
		$AppUI->setMsg( $CONFIG_FILE." ".$AppUI->_('is not writable.'), UI_MSG_ERROR );
	}
} else if(dPgetParam( $_POST, "Cancel", '' )!=''){
	$AppUI->redirect("m=system&a=viewmods");
}

$TIMECARD_CONFIG = array();
require_once( $CONFIG_FILE );

//Read the current config values from the config file and update the array.
foreach ($config_options as $key=>$value){
	$config_options[$key]['value']=$TIMECARD_CONFIG[$key];
}

// setup the title block
$titleBlock = new CTitleBlock( 'Configure TimeCard Module', 'TimeCard.png', $m, "$m.$a" );
$titleBlock->addCrumb( "?m=system", "system admin" );
$titleBlock->addCrumb( "?m=system&a=viewmods", "modules list" );
$titleBlock->show();

//$= @file( $AppUI->getConfig( 'root_dir' )."/modules/timecard/reports/$desc_file" );

?>

<form method="post">
<table class="std">
<?php
foreach ($config_options as $key=>$value){
?>
	<tr>
		<td align="left"><?=$value['description']?></td>
		<td><input type="checkbox" name="<?=$key?>" <?=$value['value']?"checked":""?>></td>
	</tr>
<?php	
}
?>
	<tr>
		<td colspan="2" align="right"><input type="Submit" name="Cancel" value="<?=$AppUI->_('Back')?>"><input type="Submit" name="Save" value="<?=$AppUI->_('Save')?>"></td>
	</tr>
</table>
</form>
